export interface AlectoLangDefs{
    startup:string
    reoverride:string
    initdone:string
    loadDeps:string
    loadComments:string
    starts:string
    download:string
    downloaded:string
    bundle:string
    alldone:string
    runLabel:string
    about:string
    error:string
    langChanged:string
    captchaRej:string
    abstractImage:string
    snapshot:string
    cors:string
}

export var AlectoDefaultLang : AlectoLangDefs = {
    startup:"",
    reoverride:"",
    initdone:"",
    loadDeps:"",
    loadComments:"",
    starts:"",
    download:"",
    downloaded:"",
    bundle:"",
    alldone:"",
    runLabel:"",
    about:"",
    error:"",
    langChanged:"",
    captchaRej:"",
    abstractImage:"",
    snapshot:"",
    cors:""
}